name: ci
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - working-directory: dev-ci
        run: |
          docker build --tag superstructor/dev-ci .
          docker history superstructor/dev-ci
