name: cd
on: [push]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build registry.hub.docker.com/superstructor/clojure:openjdk-11-lein-2.9.1-node-browser
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: superstructor/clojure:openjdk-11-lein-2.9.1-node-browser
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          workdir: clojure/openjdk-11-lein/node-browsers
      - name: Build docker.pkg.github.com/superstructor/dockerfiles/clojure:openjdk-11-lein-2.9.1-node-browser
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: superstructor/dockerfiles/clojure:openjdk-11-lein-2.9.1-node-browser
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          workdir: clojure/openjdk-11-lein/node-browsers
