name: cd
on: [push]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build registry.hub.docker.com/superstructor/clojure:openjdk-11-lein-2.9.1-node-browsers
        uses: elgohr/Publish-Docker-Github-Action@2.9
        with:
          name: superstructor/clojure:openjdk-11-lein-2.9.1-node-browsers
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          workdir: clojure/openjdk-11-lein/node-browsers
      - name: Build docker.pkg.github.com/superstructor/dockerfiles/clojure:openjdk-11-lein-2.9.1-node-browsers
        uses: elgohr/Publish-Docker-Github-Action@2.9
        with:
          name: superstructor/dockerfiles/clojure:openjdk-11-lein-2.9.1-node-browsers
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          workdir: clojure/openjdk-11-lein/node-browsers
      - name: Build registry.hub.docker.com/superstructor/python:3.6.7
        uses: elgohr/Publish-Docker-Github-Action@2.9
        with:
          name: superstructor/python:3.6.7
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          workdir: python/3.6.7
      - name: Build docker.pkg.github.com/superstructor/dockerfiles/python:3.6.7
        uses: elgohr/Publish-Docker-Github-Action@2.9
        with:
          name: superstructor/dockerfiles/python:3.6.7
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          workdir: python/3.6.7
