name: cd
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build registry.hub.docker.com/superstructor/clojure
        uses: elgohr/Publish-Docker-Github-Action@2.9
        with:
          name: superstructor/clojure
          tag_semver: true
          registry: registry.hub.docker.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          workdir: clojure
      - name: Build docker.pkg.github.com/superstructor/clojure
        uses: elgohr/Publish-Docker-Github-Action@2.9
        with:
          name: superstructor/clojure
          tag_semver: true
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          workdir: clojure